#!/bin/csh

# run this script to update publications and thesis

updateBiblio > Publications.html
updateThesis > Thesis_supervised.html

cp Publications.html ../../index.php/.
cp Thesis_supervised.html ../../index.php/.
